### ISSUE TITLE
1332_snippet.png is missing

### ISSUE THREAD

**Issue by maky-hnou** [VasilyShcherbinin/Text-OCR#1]
After running `python extract_char.py`, I got this error: 
```
Traceback (most recent call last):
  File "extract_char.py", line 230, in <module>
    os.remove('Text-OCR/vs00162_src/AI_PRINT/testingChar/1332_snippet.png')
FileNotFoundError: [Errno 2] No such file or directory: './testingChar/1332_snippet.png'
```
I checked the **testingChar** folder, and I found that **1332_snippet.png** is missing.

**Comment by VasilyShcherbinin** [comment]
Added 1332_snippet.png file to AI_PRINT/testingChar.

**Comment by Srinivasa95** [comment]
how do i test the ocr/testing files. When i try to run the png file it says as 
ValueError: X has 114048 features per sample; expecting 96
Kindly help me with this issue.
Thanks.
